version: '3.8'
services:
  nextcloud:
    image: nextcloud
    container_name: nextcloud_home
    ports:
      - '3000:80'
    volumes:
      - '/opt/nextcloud_data/nextcloud:/var/www/html'
      - '/opt/nextcloud_data/apps:/var/www/html/custom_apps'
      - '/opt/nextcloud_data/config:/var/www/html/config'
      - '/opt/nextcloud_data/data:/var/www/html/data'
      - '/opt/nextcloud_data/theme:/var/www/html/themes/YOUR_THEME'
    environment:
      - MYSQL_PASSWORD=failure_point32
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud
      - MYSQL_HOST=mysql
      - NEXTCLOUD_ADMIN_USER=locadm
      - NEXTCLOUD_ADMIN_PASSWORD=whoiamiamadmin
      #- NEXTCLOUD_TRUSTED_DOMAINS=192.168.0.46
    restart: unless-stopped
    networks:
      - internet
      - localnet
      
  mysql:
    image: mysql:latest
    container_name: mysql_nextcloud
    ports:
      - '3306:3306'
    volumes:
      - '/opt/mysql_data:/var/lib/mysql'
    environment:
      - MYSQL_ROOT_PASSWORD=rootforgood
      - MYSQL_PASSWORD=failure_point32
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud
    restart: unless-stopped
    networks:
      - localnet

networks:
  internet:
    name: internet
    driver: bridge
  localnet:
    name: localnet
    driver: bridge
